### ISSUE TITLE
install this project on my VPS

### ISSUE THREAD

**Issue by mesame** [fathonix/ChatGPT-WhatsApp#3]
I'm trying to run this on VPS 
centos 7 , 
i installed Node.js and NPM

 After trying to run this error appears
`> npx vite-node src/index.ts

(node:2371) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.<anonymous> (/home/ai/public_html/node_modules/vite-node/vite-node.mjs:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at findNodeScript.then.existing (/usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
(node:2371) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2371) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by fathonix** [comment]
Could you give the version of the installed Node.js and NPM?
